name: CI/CD

on: 
  push:
  pull_request:

env:
  NODE_VERSION: 16.x
  AWS_REGION : "eu-west-1"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : "epaper-test"
    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_VUE_APP_API_URL: "https://api.epaper.opendatahub.testingmachine.eu"
          X_VUE_APP_KEYCLOAK_URL: "https://auth.opendatahub.testingmachine.eu/auth"
          X_VUE_APP_KEYCLOAK_REALM: "noi"
          X_VUE_APP_KEYCLOAK_CLIENT_ID: "it.bz.opendatahub.epaper.web"
          X_VUE_APP_KEYCLOAK_RESOURCE_CLIENT_ID: "it.bz.opendatahub.epaper.api"

      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}

      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  # PROD STILL NOT READY
  # deploy-prod:
  #   runs-on: ubuntu-20.04
  #   if: github.ref == 'refs/heads/prod'
  #   needs: test
  #   concurrency: deploy-prod
  #   env:
  #     AWS_S3_BUCKET_NAME : "epaper-prod"
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Create .env file
  #       uses: noi-techpark/github-actions/env-file@v2
  #       env:
  #         X_VUE_APP_API_URL: "https://api.epaper.opendatahub.testingmachine.eu"
  #         X_VUE_APP_KEYCLOAK_URL: "https://auth.opendatahub.testingmachine.eu/auth"
  #         X_VUE_APP_KEYCLOAK_REALM: "noi"
  #         X_VUE_APP_KEYCLOAK_CLIENT_ID: "it.bz.opendatahub.epaper.web"
  #         X_VUE_APP_KEYCLOAK_RESOURCE_CLIENT_ID: "it.bz.opendatahub.epaper.api"

  #     - uses: noi-techpark/github-actions/npm-build@v2
  #       with:
  #         build-command: npm run build
  #         node-version: ${{env.NODE_VERSION}}

  #     - name: Sync to S3 bucket
  #       uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
  #       with:
  #         access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
  #         secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
  #         region: ${{ env.AWS_REGION }}
  #         s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
  #         folder: ./dist
         

